# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_url',
            new_name='description',
        ),
    ]
