# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('img_url', models.URLField(max_length=50)),
                ('repo_url', models.URLField(max_length=50)),
                ('project_url', models.URLField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('technologies', models.CharField(max_length=100)),
            ],
        ),
    ]
